export enum HomePageActionType {
  DELETE_SEARCH = "DELETE_SEARCH",
  SEARCH_QUERY = "NEW_SEARCH_QUERY",
  SEARCH_QUERY_PENDING = "NEW_SEARCH_QUERY_PENDING",
  SEARCH_QUERY_FULFILLED = "NEW_SEARCH_QUERY_FULFILLED",
  SEARCH_QUERY_REJEXTED = "NEW_SEARCH_QUERY_REJEXTED",
  CHANGE_LAYOUT = "CHANGE_LAYOUT"
}
